### PR TITLE
BUG: Fix module extraction `Array().concat()` bundles.

### LINKED ISSUE #53: BUG: Handle `Array().concat()` version of `webpackJsonp`
From @ryan-codingintrigue in https://github.com/FormidableLabs/webpack-dashboard/issues/182#issuecomment-336121278

> @ryan-roemer I've been getting this error too since `1.0.0-7`. I have a pretty big SPA, so it's been hard to get a repro of the issue, but I think I've narrowed it down to something to do with my bundle splitting.
> 
> My minimal example outputs a few bundles like this:
> ```javascript
> // bundle.0.js
> webpackJsonp([0],[ ...
> // bundle.1.js
> webpackJsonp([1],{ ...
> // etc.
> ```
> However, my large SPA's bundles look like this:
> ```javascript
> // bundle.0.js
> webpackJsonp([0],Array(171).concat([
> // bundle.1.js
> webpackJsonp([1],Array(171).concat([
> ```
> 
> I haven't been able to identify why, but it looks like this is causing the inspectpack [parser/index.js#179](https://github.com/FormidableLabs/inspectpack/blob/master/lib/parser/index.js#L179) to be hit, making the parser assume throw that there "*No code sections found*"

The issue looks to be in `getJsonpModules`, where we've found a `webpackJsonp`, but expect second arg to be `[]` instead of `Array(NUM).concat([])`: https://github.com/FormidableLabs/inspectpack/blob/master/lib/parser/find-module-expression.js#L17-L22

### PR DESCRIPTION
**Pull request by ryan-roemer**
* Fixes #53 

/cc @tptee @carlospaelinck @ryan-codingintrigue

### CODE REVIEW

File: lib/parser/index.js [hunk 1]
```diff
@@ -176,6 +176,14 @@ const extractModules = function (node, rawCode, opts) {
     return extractFromObjectExpression(node, rawCode, opts);
   }
 
+  // Structure: `Array(NUM).concat([/*actual modules array*/])`
```
Comment (tptee) [inline lib/parser/index.js]: Bundle output never fails to deliver new surprises :trollface:

**Comment by ryan-roemer** [comment]
Released in `inspectpack@2.2.2`
